-- ==============================================================================
-- 2. CORE SOCIAL TABLES
-- ==============================================================================

-- A. Profiles
CREATE TABLE public.profiles (
    id              uuid         REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
    email           varchar(255) UNIQUE NOT NULL,
    name            varchar(255),
    avatar_url      text,
    bio             text,
    fcm_token       text,
    last_active_at  timestamptz,
    created_at      timestamptz  DEFAULT now() NOT NULL,
    updated_at      timestamptz  DEFAULT now() NOT NULL
);

-- B. Follows
CREATE TABLE public.follows (
    follower_id  uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    following_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at   timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY (follower_id, following_id),
    CONSTRAINT cant_follow_self CHECK (follower_id != following_id)
);

-- C. User Watchlist
CREATE TABLE public.user_watchlist (
    user_id      uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    stock_symbol text NOT NULL,
    created_at   timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY (user_id, stock_symbol)
);

-- D. Posts
CREATE TABLE public.posts (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    uuid         REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    content    text,
    image_url  text,
    sentiment  varchar(10)  CHECK (sentiment IN ('bullish', 'bearish')),
    cashtags   text[],
    created_at timestamptz  DEFAULT now() NOT NULL
);

-- E. Post Votes
CREATE TABLE public.post_votes (
    user_id    uuid   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    post_id    bigint REFERENCES public.posts(id)    ON DELETE CASCADE NOT NULL,
    vote_type  int    NOT NULL CHECK (vote_type IN (1, -1)),
    created_at timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY (user_id, post_id)
);

-- F. Bookmarks
CREATE TABLE public.bookmarks (
    user_id    uuid   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    post_id    bigint REFERENCES public.posts(id)    ON DELETE CASCADE NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY (user_id, post_id)
);

-- G. Comments
CREATE TABLE public.comments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    uuid   REFERENCES public.profiles(id)  ON DELETE CASCADE NOT NULL,
    post_id    bigint REFERENCES public.posts(id)     ON DELETE CASCADE NOT NULL,
    parent_id  bigint REFERENCES public.comments(id)  ON DELETE CASCADE,  -- NULL = root comment
    content    text   NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- H. Comment Votes
CREATE TABLE public.comment_votes (
    user_id    uuid   REFERENCES public.profiles(id)   ON DELETE CASCADE NOT NULL,
    comment_id bigint REFERENCES public.comments(id)   ON DELETE CASCADE NOT NULL,
    vote_type  int    NOT NULL CHECK (vote_type IN (1, -1)),
    created_at timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY (user_id, comment_id)
);

-- I. Notifications
CREATE TABLE public.notifications (
    id           bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id uuid    REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    sender_id    uuid    REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    resource_id  bigint  NOT NULL,
    type         text    NOT NULL CHECK (type IN ('comment', 'reply', 'like', 'follow')),
    title        text,
    body         text,
    metadata     jsonb   DEFAULT '{}'::jsonb,
    is_read      boolean DEFAULT false,
    created_at   timestamptz DEFAULT now() NOT NULL
);
