-- ==============================================================================
-- 3. STOCK & MARKET TABLES & AI
-- ==============================================================================

-- A. Stocks master table
CREATE TABLE public.stocks (
    id                bigint       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    symbol            varchar(10)  UNIQUE NOT NULL,
    company_name_en   varchar(255) NOT NULL,
    company_name_ar   varchar(255),
    sector            varchar(100),
    description       text,
    total_shares      bigint,
    prev_close        float4       DEFAULT 0.0,
    isin_code         varchar(50),
    logo_url          text,
    listing_date      date,
    website           varchar(255),
    candle_table_name varchar(50)  NOT NULL,
    created_at        timestamptz  DEFAULT now()
);

-- B. Candle tables (one per ticker — Egyptian stocks)
DO $$
DECLARE
    ticker TEXT;
    tickers TEXT[] := ARRAY[
        'tmgh','comi','fwry','abuk','east','efih','emfd','etel','expa','hrho',
        'iron','oras','swdy','clho','isph','skpc','amoc','alcn','cira','orwe',
        'jufo','efid','phdc','adib','ccap','raya','oih','csag','teeg','dscw',
        'egal','arcc','egx30','egx70ewi','gold','silver'
    ];
BEGIN
    FOREACH ticker IN ARRAY tickers LOOP
        EXECUTE format('
            CREATE TABLE IF NOT EXISTS %I (
                timestamp   TIMESTAMPTZ NOT NULL,
                open        FLOAT4,
                high        FLOAT4,
                low         FLOAT4,
                close       FLOAT4,
                volume      BIGINT,
                timeframe   VARCHAR(5)  NOT NULL,
                created_at  TIMESTAMPTZ DEFAULT now(),
                PRIMARY KEY (timestamp, timeframe)
            );', ticker || '_candles');
    END LOOP;
END $$;

-- C. Market daily summary
CREATE TABLE public.market_history (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date   date   NOT NULL,
    market_cap   text,
    value_traded text,
    updated_at   timestamptz DEFAULT now()
);

-- D. Gold / Silver spot prices (buy & sell per karat/unit)
CREATE TABLE public.materials_prices (
    id              serial PRIMARY KEY,
    timestamp       timestamptz DEFAULT now(),
    p24_buy         numeric(10,2), p24_sell         numeric(10,2),
    p21_buy         numeric(10,2), p21_sell         numeric(10,2),
    p18_buy         numeric(10,2), p18_sell         numeric(10,2),
    ounce_buy       numeric(12,2), ounce_sell       numeric(12,2),
    gold_pound_buy  numeric(12,2), gold_pound_sell  numeric(12,2),
    bar_50g_buy     numeric(12,2), bar_50g_sell     numeric(12,2),
    bar_100g_buy    numeric(12,2), bar_100g_sell    numeric(12,2),
    bar_250g_buy    numeric(15,2), bar_250g_sell    numeric(15,2)
);

-- E. Stock news (with sentiment label)
CREATE TABLE IF NOT EXISTS public.stock_news (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    stock_id        bigint REFERENCES public.stocks(id) ON DELETE CASCADE,
    title           text   NOT NULL,
    description     text,
    content         text,
    url             text   UNIQUE,
    source          varchar(100),
    sentiment_label varchar(50),
    published_at    timestamptz,
    created_at      timestamptz DEFAULT now()
);

-- F. AI Predictions
CREATE TABLE public.ai_predictions (
    id          bigint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      varchar(10) REFERENCES public.stocks(symbol) ON DELETE CASCADE NOT NULL,
    close_price numeric    NOT NULL,
    probability numeric    NOT NULL,
    created_at  timestamptz DEFAULT now() NOT NULL
);

-- ==============================================================================
-- G. Stock Messages (Chat/Discussion per stock)
-- ==============================================================================
CREATE TABLE public.stock_messages (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    stock_id   bigint REFERENCES public.stocks(id) ON DELETE CASCADE NOT NULL,
    user_id    uuid   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL, -- يفضل نربطه بجدول profiles بدل auth.uid
    username   varchar(100),
    content    text   NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);



-- 1. إضافة العواميد الجديدة لجدول ai_predictions
ALTER TABLE public.ai_predictions
    ADD COLUMN IF NOT EXISTS prediction_date date,
    ADD COLUMN IF NOT EXISTS open_price float8,
    ADD COLUMN IF NOT EXISTS high_price float8,
    ADD COLUMN IF NOT EXISTS low_price float8,
    ADD COLUMN IF NOT EXISTS volume float8,
    ADD COLUMN IF NOT EXISTS usd_egp_rate float8,
    ADD COLUMN IF NOT EXISTS gold_egp float8,
    ADD COLUMN IF NOT EXISTS close_usd float8,
    ADD COLUMN IF NOT EXISTS log_ret_usd float8,
    ADD COLUMN IF NOT EXISTS price_velocity_usd float8,
    ADD COLUMN IF NOT EXISTS gold_usd float8,
    ADD COLUMN IF NOT EXISTS gold_log_ret float8,
    ADD COLUMN IF NOT EXISTS gold_velocity float8,
    ADD COLUMN IF NOT EXISTS gold_ret_lag1 float8,
    ADD COLUMN IF NOT EXISTS interest_rate float8,
    ADD COLUMN IF NOT EXISTS ir_change float8,
    ADD COLUMN IF NOT EXISTS log_ret_usd_lag1 float8,
    ADD COLUMN IF NOT EXISTS log_ret float8,
    ADD COLUMN IF NOT EXISTS price_velocity float8,
    ADD COLUMN IF NOT EXISTS volume_sma_50 float8,
    ADD COLUMN IF NOT EXISTS rvol_50 float8,
    ADD COLUMN IF NOT EXISTS day_sin float8,
    ADD COLUMN IF NOT EXISTS day_cos float8,
    ADD COLUMN IF NOT EXISTS ema_9 float8,
    ADD COLUMN IF NOT EXISTS dist_ema_9 float8,
    ADD COLUMN IF NOT EXISTS ema_10 float8,
    ADD COLUMN IF NOT EXISTS dist_ema_10 float8,
    ADD COLUMN IF NOT EXISTS ema_20 float8,
    ADD COLUMN IF NOT EXISTS dist_ema_20 float8,
    ADD COLUMN IF NOT EXISTS ema_21 float8,
    ADD COLUMN IF NOT EXISTS dist_ema_21 float8,
    ADD COLUMN IF NOT EXISTS ema_31 float8,
    ADD COLUMN IF NOT EXISTS dist_ema_31 float8,
    ADD COLUMN IF NOT EXISTS ema_50 float8,
    ADD COLUMN IF NOT EXISTS dist_ema_50 float8,
    ADD COLUMN IF NOT EXISTS below_ema9 float8,
    ADD COLUMN IF NOT EXISTS ema_spread float8,
    ADD COLUMN IF NOT EXISTS ema_cross_signal float8,
    ADD COLUMN IF NOT EXISTS rsi float8,
    ADD COLUMN IF NOT EXISTS rsi_diff float8,
    ADD COLUMN IF NOT EXISTS macd_hist float8,
    ADD COLUMN IF NOT EXISTS atr_pct float8,
    ADD COLUMN IF NOT EXISTS bb_width float8,
    ADD COLUMN IF NOT EXISTS log_ret_lag1 float8,
    ADD COLUMN IF NOT EXISTS rsi_lag1 float8,
    ADD COLUMN IF NOT EXISTS usd_shock float8,
    ADD COLUMN IF NOT EXISTS rate_hike_flag float8,
    ADD COLUMN IF NOT EXISTS rate_drop_flag float8,
    ADD COLUMN IF NOT EXISTS composite_momentum float8,
    ADD COLUMN IF NOT EXISTS noise float8,
    ADD COLUMN IF NOT EXISTS momentum_status varchar(100),
    ADD COLUMN IF NOT EXISTS macd_status varchar(100),
    ADD COLUMN IF NOT EXISTS volatility_status varchar(100),
    ADD COLUMN IF NOT EXISTS consensus_up_pct float8,
    ADD COLUMN IF NOT EXISTS consensus_down_pct float8,
    ADD COLUMN IF NOT EXISTS overall_trend varchar(50),
    ADD COLUMN IF NOT EXISTS ml_signal varchar(10),
    ADD COLUMN IF NOT EXISTS model_version varchar(50);

-- 2. إضافة قيد يمنع التكرار لنفس السهم في نفس اليوم (عشان أمر Upsert يشتغل صح)
-- (ملاحظة: لو الجدول فيه داتا قديمة متكررة، امسح المتكرر الأول قبل ما ترن السطر ده)
ALTER TABLE public.ai_predictions ADD CONSTRAINT unique_prediction_date UNIQUE (symbol, prediction_date);
