-- ==============================================================================
-- 3. STOCK & MARKET TABLES & AI
-- ==============================================================================

-- A. Stocks master table
CREATE TABLE public.stocks (
    id                bigint       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    symbol            varchar(10)  UNIQUE NOT NULL,
    company_name_en   varchar(255) NOT NULL,
    company_name_ar   varchar(255),
    sector            varchar(100),
    description       text,
    total_shares      bigint,
    prev_close        float4       DEFAULT 0.0,
    isin_code         varchar(50),
    logo_url          text,
    listing_date      date,
    website           varchar(255),
    candle_table_name varchar(50)  NOT NULL,
    created_at        timestamptz  DEFAULT now()
);

-- B. Candle tables (one per ticker — Egyptian stocks)
DO $$
DECLARE
    ticker TEXT;
    tickers TEXT[] := ARRAY[
        'tmgh','comi','fwry','abuk','east','efih','emfd','etel','expa','hrho',
        'iron','oras','swdy','clho','isph','skpc','amoc','alcn','cira','orwe',
        'jufo','efid','phdc','adib','ccap','raya','oih','csag','teeg','dscw',
        'egal','arcc','egx30','egx70ewi','gold','silver'
    ];
BEGIN
    FOREACH ticker IN ARRAY tickers LOOP
        EXECUTE format('
            CREATE TABLE IF NOT EXISTS %I (
                timestamp   TIMESTAMPTZ NOT NULL,
                open        FLOAT4,
                high        FLOAT4,
                low         FLOAT4,
                close       FLOAT4,
                volume      BIGINT,
                timeframe   VARCHAR(5)  NOT NULL,
                created_at  TIMESTAMPTZ DEFAULT now(),
                PRIMARY KEY (timestamp, timeframe)
            );', ticker || '_candles');
    END LOOP;
END $$;

-- C. Market daily summary
CREATE TABLE public.market_history (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date   date   NOT NULL,
    market_cap   text,
    value_traded text,
    updated_at   timestamptz DEFAULT now()
);

-- D. Gold / Silver spot prices (buy & sell per karat/unit)
CREATE TABLE public.materials_prices (
    id              serial PRIMARY KEY,
    timestamp       timestamptz DEFAULT now(),
    p24_buy         numeric(10,2), p24_sell         numeric(10,2),
    p21_buy         numeric(10,2), p21_sell         numeric(10,2),
    p18_buy         numeric(10,2), p18_sell         numeric(10,2),
    ounce_buy       numeric(12,2), ounce_sell       numeric(12,2),
    gold_pound_buy  numeric(12,2), gold_pound_sell  numeric(12,2),
    bar_50g_buy     numeric(12,2), bar_50g_sell     numeric(12,2),
    bar_100g_buy    numeric(12,2), bar_100g_sell    numeric(12,2),
    bar_250g_buy    numeric(15,2), bar_250g_sell    numeric(15,2)
);

-- E. Stock news (with sentiment label)
CREATE TABLE IF NOT EXISTS public.stock_news (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    stock_id        bigint REFERENCES public.stocks(id) ON DELETE CASCADE,
    title           text   NOT NULL,
    description     text,
    content         text,
    url             text   UNIQUE,
    source          varchar(100),
    sentiment_label varchar(50),
    published_at    timestamptz,
    created_at      timestamptz DEFAULT now()
);

-- F. AI Predictions
CREATE TABLE public.ai_predictions (
    id          bigint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      varchar(10) REFERENCES public.stocks(symbol) ON DELETE CASCADE NOT NULL,
    close_price numeric    NOT NULL,
    probability numeric    NOT NULL,
    created_at  timestamptz DEFAULT now() NOT NULL
);

-- ==============================================================================
-- G. Stock Messages (Chat/Discussion per stock)
-- ==============================================================================
CREATE TABLE public.stock_messages (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    stock_id   bigint REFERENCES public.stocks(id) ON DELETE CASCADE NOT NULL,
    user_id    uuid   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL, -- يفضل نربطه بجدول profiles بدل auth.uid
    username   varchar(100),
    content    text   NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);