-- ==============================================================================
-- 4. PORTFOLIO / PAPER-TRADING TABLES
-- ==============================================================================

-- A. Virtual wallet (starts with 100K EGP)
CREATE TABLE public.user_wallets (
    user_id         uuid    REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
    balance         numeric DEFAULT 100000.00,
    initial_balance numeric DEFAULT 100000.00,
    created_at      timestamptz DEFAULT now()
);

-- B. Holdings
CREATE TABLE public.user_holdings (
    user_id       uuid   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    symbol        text   NOT NULL,
    quantity      numeric NOT NULL DEFAULT 0,
    average_price numeric NOT NULL DEFAULT 0,
    updated_at    timestamptz DEFAULT now(),
    PRIMARY KEY (user_id, symbol)
);

-- C. Transaction history
CREATE TABLE public.user_transactions (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        uuid   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    symbol         text   NOT NULL,
    type           text   CHECK (type IN ('buy', 'sell')),
    quantity       numeric NOT NULL,
    price          numeric NOT NULL,
    total_value    numeric NOT NULL,
    execution_type text    DEFAULT 'manual' CHECK (execution_type IN ('manual', 'auto_protection')),
    created_at     timestamptz DEFAULT now()
);

-- D. Price protection rules (stop-loss / alerts)
CREATE TABLE public.user_protection_rules (
    id                     bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                uuid    REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    symbol                 text    NOT NULL,
    alert_percentage       numeric DEFAULT 5.0,
    liquidation_percentage numeric DEFAULT 10.0,
    is_alert_enabled       boolean DEFAULT false,
    is_sell_enabled        boolean DEFAULT false,
    last_alert_sent_at     timestamptz,
    created_at             timestamptz DEFAULT now(),
    UNIQUE (user_id, symbol)
);

-- E. Onboarding / risk profile
CREATE TABLE public.user_risk_profiles (
    user_id          uuid     REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
    experience_level text,
    investment_goal  text,
    risk_score       int      DEFAULT 50,
    selected_sectors text[],
    created_at       timestamptz DEFAULT now() NOT NULL,
    updated_at       timestamptz DEFAULT now() NOT NULL
);