-- ==============================================================================
-- Notification System Fix - Populate Metadata with post_id
-- ==============================================================================
-- This migration ensures that database triggers properly populate the metadata
-- field with post_id for navigation purposes in the Flutter app.

-- ==============================================================================
-- 1. Cleanup - Drop existing triggers and functions
-- ==============================================================================
DROP TRIGGER IF EXISTS on_comment_created ON public.comments;
DROP TRIGGER IF EXISTS on_post_like ON public.post_votes;
DROP TRIGGER IF EXISTS on_follow_created ON public.follows;
DROP TRIGGER IF EXISTS on_comment_like ON public.comment_votes;

DROP FUNCTION IF EXISTS public.handle_new_comment_notification CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_like_notification CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_follow_notification CASCADE;
DROP FUNCTION IF EXISTS public.handle_comment_like_notification CASCADE;

-- ==============================================================================
-- 2. Update Table Structure
-- ==============================================================================

-- Add FCM token to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS fcm_token text;

-- Create or update notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    sender_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    resource_id bigint NOT NULL, -- post_id or comment_id
    type text NOT NULL CHECK (type IN ('comment', 'reply', 'like', 'follow')),
    title text,
    body text,
    metadata jsonb DEFAULT '{}'::jsonb, -- CRITICAL: stores post_id for navigation
    is_read boolean DEFAULT false,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add metadata column if it doesn't exist (for existing tables)
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;

-- ==============================================================================
-- 3. Enable RLS and Create Policies
-- ==============================================================================
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Users can view own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can update own notifications" ON public.notifications;

-- Recreate policies
CREATE POLICY "Users can view own notifications" 
    ON public.notifications FOR SELECT 
    USING (auth.uid() = recipient_id);

CREATE POLICY "Users can update own notifications" 
    ON public.notifications FOR UPDATE 
    USING (auth.uid() = recipient_id);

-- ==============================================================================
-- 4. Trigger Functions - The Core Logic
-- ==============================================================================

-- A. Comment & Reply Notifications
CREATE OR REPLACE FUNCTION public.handle_new_comment_notification() 
RETURNS TRIGGER AS $$
DECLARE
    post_owner_id uuid;
    parent_owner_id uuid;
    sender_name text;
BEGIN
    -- Get sender name
    SELECT name INTO sender_name FROM public.profiles WHERE id = new.user_id;
    
    -- Case 1: Reply to a comment
    IF new.parent_id IS NOT NULL THEN
        SELECT user_id INTO parent_owner_id FROM public.comments WHERE id = new.parent_id;
        
        -- Don't notify yourself
        IF parent_owner_id != new.user_id THEN
            INSERT INTO public.notifications (recipient_id, sender_id, resource_id, type, title, body, metadata)
            VALUES (
                parent_owner_id, 
                new.user_id, 
                new.post_id, 
                'reply', 
                'New Reply', 
                sender_name || ' replied to your comment',
                jsonb_build_object('post_id', new.post_id, 'comment_id', new.id)
            );
        END IF;
    
    -- Case 2: Comment on a post
ELSE
        SELECT user_id INTO post_owner_id FROM public.posts WHERE id = new.post_id;
        
        -- Don't notify yourself
        IF post_owner_id != new.user_id THEN
            INSERT INTO public.notifications (recipient_id, sender_id, resource_id, type, title, body, metadata)
            VALUES (
                post_owner_id, 
                new.user_id, 
                new.post_id, 
                'comment', 
                'New Comment', 
                sender_name || ' commented on your post',
                jsonb_build_object('post_id', new.post_id)
            );
        END IF;
    END IF;
    
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- B. Post Like Notifications
CREATE OR REPLACE FUNCTION public.handle_new_like_notification() 
RETURNS TRIGGER AS $$
DECLARE
    post_owner_id uuid;
    sender_name text;
BEGIN
    -- Only create notification for likes (vote_type = 1), not dislikes
    IF new.vote_type = 1 THEN
        SELECT name INTO sender_name FROM public.profiles WHERE id = new.user_id;
        SELECT user_id INTO post_owner_id FROM public.posts WHERE id = new.post_id;

        -- Don't notify yourself
        IF post_owner_id != new.user_id THEN
            INSERT INTO public.notifications (recipient_id, sender_id, resource_id, type, title, body, metadata)
            VALUES (
                post_owner_id, 
                new.user_id, 
                new.post_id, 
                'like', 
                'New Like', 
                sender_name || ' liked your post',
                jsonb_build_object('post_id', new.post_id)
            );
        END IF;
    END IF;
    
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- C. Comment Like Notifications
CREATE OR REPLACE FUNCTION public.handle_comment_like_notification() 
RETURNS TRIGGER AS $$
DECLARE
    comment_owner_id uuid;
    sender_name text;
    post_id_val bigint;
BEGIN
    -- Only create notification for likes (vote_type = 1), not dislikes
    IF new.vote_type = 1 THEN
        SELECT name INTO sender_name FROM public.profiles WHERE id = new.user_id;
        SELECT user_id, post_id INTO comment_owner_id, post_id_val 
        FROM public.comments WHERE id = new.comment_id;

        -- Don't notify yourself
        IF comment_owner_id != new.user_id THEN
            INSERT INTO public.notifications (recipient_id, sender_id, resource_id, type, title, body, metadata)
            VALUES (
                comment_owner_id, 
                new.user_id, 
                new.comment_id, 
                'like', 
                'Comment Liked', 
                sender_name || ' liked your comment',
                jsonb_build_object('post_id', post_id_val, 'comment_id', new.comment_id)
            );
        END IF;
    END IF;
    
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- D. Follow Notifications
CREATE OR REPLACE FUNCTION public.handle_new_follow_notification() 
RETURNS TRIGGER AS $$
DECLARE
    sender_name text;
BEGIN
    SELECT name INTO sender_name FROM public.profiles WHERE id = new.follower_id;

    INSERT INTO public.notifications (recipient_id, sender_id, resource_id, type, title, body, metadata)
    VALUES (
        new.following_id, 
        new.follower_id, 
        0, -- No resource_id for follows
        'follow', 
        'New Follower', 
        sender_name || ' started following you',
        jsonb_build_object('follower_id', new.follower_id)
    );
    
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==============================================================================
-- 5. Activate Triggers
-- ==============================================================================

CREATE TRIGGER on_comment_created 
    AFTER INSERT ON public.comments 
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_comment_notification();

CREATE TRIGGER on_post_like 
    AFTER INSERT ON public.post_votes 
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_like_notification();

CREATE TRIGGER on_comment_like 
    AFTER INSERT ON public.comment_votes 
    FOR EACH ROW EXECUTE PROCEDURE public.handle_comment_like_notification();

CREATE TRIGGER on_follow_created 
    AFTER INSERT ON public.follows 
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_follow_notification();

-- ==============================================================================
-- 6. Performance Indexes
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_is_read 
    ON public.notifications (recipient_id, is_read);

CREATE INDEX IF NOT EXISTS idx_notifications_created_at 
    ON public.notifications (created_at DESC);
